#include <iostream>

using namespace std;

int main()
{
    int N,M,k=4,l=4,R=0,aux=0,aux2;
    cin>>N;
    for(int i=0;i<N;i++)
    {
        cin>>M;
        if(M==1)
        {
            k-=2;
            l++;
            if(k==2&&l==2&&aux==0)
            {
                aux++;
                R++;
            }
            if(k==4&&l==1&&aux==0)
            {
                aux++;
                R++;
            }
            if(k==4&&l==2&&aux==0)
            {
                aux++;
                R++;
            }
            if(k==3&&l==5&&aux==0)
            {
                aux++;
                R++;
            }
            if(aux==0)
            {
                R++;
            }
        }
        else
        {
            if(M==2)
            {
                k--;
                l+=2;
                if(k==2&&l==2&&aux==0)
                {
                    aux++;
                    R++;
                }
                if(k==4&&l==1&&aux==0)
                {
                    aux++;
                    R++;
                }
                if(k==4&&l==2&&aux==0)
                {
                    aux++;
                    R++;
                }
                if(k==3&&l==5&&aux==0)
                {
                    aux++;
                    R++;
                }
                if(aux==0)
                {
                    R++;
                }
            }
            else
            {
                if(M==3)
                {
                    k++;
                    l+=2;
                    if(k==2&&l==2&&aux==0)
                    {
                        aux++;
                        R++;
                    }
                    if(k==4&&l==1&&aux==0)
                    {
                        aux++;
                        R++;
                    }
                    if(k==4&&l==2&&aux==0)
                    {
                        aux++;
                        R++;
                    }
                    if(k==3&&l==5&&aux==0)
                    {
                        aux++;
                        R++;
                    }
                    if(aux==0)
                    {
                        R++;
                    }
                }
                else
                {
                    if(M==4)
                    {
                        k+=2;
                        l++;
                        if(k==2&&l==2&&aux==0)
                        {
                            aux++;
                            R++;
                        }
                        if(k==4&&l==1&&aux==0)
                        {
                            aux++;
                            R++;
                        }
                        if(k==4&&l==2&&aux==0)
                        {
                            aux++;
                            R++;
                        }
                        if(k==3&&l==5&&aux==0)
                        {
                            aux++;
                            R++;
                        }
                        if(aux==0)
                        {
                            R++;
                        }
                    }
                    else
                    {
                        if(M==5)
                        {
                            k+=2;
                            l--;
                            if(k==2&&l==2&&aux==0)
                            {
                                aux++;
                                R++;
                            }
                            if(k==4&&l==1&&aux==0)
                            {
                                aux++;
                                R++;
                            }
                            if(k==4&&l==2&&aux==0)
                            {
                                aux++;
                                R++;
                            }
                            if(k==3&&l==5&&aux==0)
                            {
                                aux++;
                                R++;
                            }
                            if(aux==0)
                            {
                                R++;
                            }
                        }
                        else
                        {
                            if(M==6)
                            {
                                k++;
                                l-=2;
                                if(k==2&&l==2&&aux==0)
                                {
                                    aux++;
                                    R++;
                                }
                                if(k==4&&l==1&&aux==0)
                                {
                                    aux++;
                                    R++;
                                }
                                if(k==4&&l==2&&aux==0)
                                {
                                    aux++;
                                    R++;
                                }
                                if(k==3&&l==5&&aux==0)
                                {
                                    aux++;
                                    R++;
                                }
                                if(aux==0)
                                {
                                    R++;
                                }
                            }
                            else
                            {
                                if(M==7)
                                {
                                    k--;
                                    l-=2;
                                    if(k==2&&l==2&&aux==0)
                                    {
                                        aux++;
                                        R++;
                                    }
                                    if(k==4&&l==1&&aux==0)
                                    {
                                        aux++;
                                        R++;
                                    }
                                    if(k==4&&l==2&&aux==0)
                                    {
                                        aux++;
                                        R++;
                                    }
                                    if(k==3&&l==5&&aux==0)
                                    {
                                        aux++;
                                        R++;
                                    }
                                    if(aux==0)
                                    {
                                        R++;
                                    }
                                }
                                else
                                {
                                    if(M==8)
                                    {
                                        k-=2;
                                        l--;
                                        if(k==2&&l==2&&aux==0)
                                        {
                                            aux++;
                                            R++;
                                        }
                                        if(k==4&&l==1&&aux==0)
                                        {
                                            aux++;
                                            R++;
                                        }
                                        if(k==4&&l==2&&aux==0)
                                        {
                                            aux++;
                                            R++;
                                        }
                                        if(k==3&&l==5&&aux==0)
                                        {
